# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    network_mode: "host"
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Paudzno1

  tfocg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfocg
    ports:
      - "8080:8000"
    restart: always

  redis:
    network_mode: "host"
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    network_mode: "host"
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "register"
      RABBITMQ_DEFAULT_PASS: "register"

  elasticsearch:
    network_mode: "host"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always