# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ocg-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Paudzno1

  tfocg:
    image: tram0c/cuong:latest
    container_name: tfocg
    ports:
      - "8080:8080"
    restart: always
    volumes:
        - ./config/.env:/.env
        - ./config/config.json:/config.json

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "register"
      RABBITMQ_DEFAULT_PASS: "register"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw

volumes:
  ocg-mysql:
  esdata:
