# Use root/example as user/password credentials
version: '3.1'

services:
#  mysql:
#    container_name: db
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - "3307:3306"
#    volumes:
#      - ocg-mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: Paudzno1
#
#  tfocg:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: tfocg
#    volumes:
#      - ocg-mysql
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8000"
#    restart: always

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "register"
      RABBITMQ_DEFAULT_PASS: "register"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
    ports:
      - "9200:9200"
    restart: always