# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678

  tfocg:
    image: tfocg
    ports:
      - "8080:8000"
    restart: always